<a href="https://colab.research.google.com/github/eoooomji/python_demo_colab/blob/master/101_%ED%8C%8C%EC%9D%BC_read_write.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
#  경로 변경
%cd /content/drive/MyDrive/python_demo

/content/drive/MyDrive/python_demo


In [ ]:
!ls

 01_자료형_문제.ipynb		       gosu.txt
 01_자료형_풀이.ipynb		      '수업_파이썬 _ppt.zip'
 02_제어문_풀이.ipynb		       python_01_Mark-Down.ipynb
 02_제어문_문제.ipynb		       python_02_basic.ipynb
'03_함수형프로그래밍_문제 (1).ipynb'   python_03_statement.ipynb
 03_함수형프로그래밍_문제.ipynb        python_04_function.ipynb
'04_함수형프로그래밍_풀이 (1).ipynb'   python_06_함수형프로그래밍.ipynb
 04_함수형프로그래밍_풀이.ipynb        python_07_class.ipynb
'05_정규표현식 문제.ipynb'	       python_08_파일입출력.ipynb
'05_정규표현식 풀이.ipynb'	       python_09_정규표현식.ipynb
 100_colab_환경설정.ipynb	       python_10_numpy.ipynb
 101_파일_read_write.ipynb	       python_11_numpy.ipynb
 gosu2.txt			       python_12_numpy.ipynb
 gosu3.txt


In [ ]:
!pwd

/content/drive/MyDrive/python_demo


In [ ]:
%%writefile ./gosu.txt
hello
안녕

Writing ./gosu.txt


In [ ]:
open('./gosu.txt')

<_io.TextIOWrapper name='./gosu.txt' mode='r' encoding='UTF-8'>

## 1. python

### open('파일경로', '모드')

- 모드  

  (1) w : 쓰기모드 - 파일에 내용을 쓸 때 사용  

  (2) r : 읽기모드 - 파일에 내용을 읽을 때 사용  

  (3) a : 추가모드 - 파일에 내용을 추가할 때 사용

- 파일의 형태 2가지  
  
  (1) 사람 기준(txt)

  (2) 기계 기준(binary)

In [ ]:
# wb : write binary
# 쓰기모드로 파일을 불러오며, binary로 저장한다는 의미이다.
a = open('./gosu2.txt', 'wb')

In [ ]:
# 'hello'의 타입은 'str'이므로 저장할 수 없다.
# -> binary로 설정이 되어있기때문에
a.write('hello')

TypeError: ignored

In [ ]:
a.write(b'hello')

5

In [ ]:
a.close()

저장한 gosu2.txt 파일을 읽어오기

In [ ]:
b = open('./gosu2.txt')

In [ ]:
next(b)

'hello'

In [ ]:
b.close()

### with

- with 구문은 시작할 때 enter, 종료할때 __exit를 자동으로 실행한다.

- exit가 실행되었기 때문에 close()를 작성 안해도 된다.

- write가 끝난 후 write()를 하면 'write to closed file' 에러가 발생한다.

In [ ]:
with open('./gosu3.txt', 'wb') as c:
  c.write(b'aaa')
  c.write(b'bbb')

In [ ]:
# ValueError 이미 종료가 되어 빠져나와서 더 이상 작성이 안된다.
c.write(b'ccc')

ValueError: ignored

In [ ]:
with open('./gosu3.txt') as c:
  print(c.read())

aaabbb


## 2. numpy

- 자체적으로 저장과 불러오는 기능을 지원한다.

In [ ]:
import numpy as np

In [ ]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

numpy의 데이터를 파일에 저장한다.

ndata1.npy로 저장된다.

array 객체 하나는 save()로 저장할 수 있다.

확장자는 자동으로 npy가 붙는다.

In [ ]:
np.save('./ndata1', a)

numpy의 파일을 읽어온다.

읽어올 때는 npy확장자를 붙여서 읽어와야 한다.

load()를 사용하면 된다.

In [ ]:
# b = np.load('./ndata1') 확장자 없이 불러오게 되면 오류가 발생한다.
b = np.load('./ndata1.npy')
b

array([0, 1, 2, 3, 4])

In [ ]:
print(type(b))

<class 'numpy.ndarray'>


savez는 여러개의 array를 저장할 수 있다.

확장자는 자동으로 npz가 붙는다.

In [ ]:
b = np.array([1, 2, 3, 4, 5])
c = np.array([6, 7, 8, 9, 10])

In [ ]:
np.savez('./ndata2', b, c)

In [ ]:
d = np.load('./ndata2.npz')
d

In [ ]:
print(type(d))
print(dir(d))

<class 'numpy.lib.npyio.NpzFile'>
['__abstractmethods__', '__class__', '__contains__', '__del__', '__delattr__', '__dict__', '__dir__', '__doc__', '__enter__', '__eq__', '__exit__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__reversed__', '__setattr__', '__sizeof__', '__slots__', '__str__', '__subclasshook__', '__weakref__', '_abc_impl', '_files', 'allow_pickle', 'close', 'f', 'fid', 'files', 'get', 'items', 'iteritems', 'iterkeys', 'keys', 'pickle_kwargs', 'values', 'zip']


diction 방식으로 저장된 객체를 가져올 수 있다.

In [ ]:
d.files

['arr_0', 'arr_1']

In [ ]:
print(d['arr_0'])
print(d['arr_1'])

[1 2 3 4 5]
[ 6  7  8  9 10]


## pandas

In [ ]:
import pandas as pd

In [ ]:
num = np.array([[1, 2, 3], [4, 5, 6]])
my_df = pd.DataFrame(num)
my_df

0  1  2
0  1  2  3
1  4  5  6

In [ ]:
# pandas에 데이터 저장
my_df.to_csv('./ndata.csv', sep = '.')

In [ ]:
# pandas에서 데이터 읽어오기
a = pd.read_csv('./ndata.csv', header = None)
a

0
0   .0.1.2
1  0.1.2.3
2  1.4.5.6