<a href="https://colab.research.google.com/github/eoooomji/python_demo_colab/blob/master/python_22_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

### 버전 확인

In [ ]:
# python 버전
import sys

print(sys.version)

!python --version

3.8.16 (default, Dec  7 2022, 01:12:13) 
[GCC 7.5.0]
Python 3.8.16


In [ ]:
# numpy 버전
np.__version__

'1.21.6'

In [ ]:
# pandas
pd.__version__

'1.3.5'

In [ ]:
# 현재 구글 colab 에서 제공되는 라이브러리
!pip freeze

numpy datatype : ndarry, matrix

pandas datatype : Series, DataFrame (행렬)

In [2]:
## 구글 드라이브 연결
from google.colab import drive
drive.mount('/content/drive')

#  경로 변경
%cd /content/drive/MyDrive/python_demo

Mounted at /content/drive
/content/drive/MyDrive/python_demo


In [3]:
%ls

 01_자료형_풀이.ipynb
 01_자료형_문제.ipynb
 02_제어문_풀이.ipynb
 02_제어문_문제.ipynb
 03_함수형프로그래밍_문제.ipynb
 04_함수형프로그래밍_풀이.ipynb
'05_정규표현식 풀이.ipynb'
'05_정규표현식 문제.ipynb'
 100_colab_환경설정.ipynb
 101_파일_read_write.ipynb
 data_crowing/
 gosu2.txt
 gosu3.txt
 gosu.txt
 ndata1.npy
 ndata2.npz
 ndata.csv
 pdsample/
'수업_파이썬 _ppt.zip'
 python_01_Mark-Down.ipynb
 python_02_basic.ipynb
 python_03_statement.ipynb
 python_04_function.ipynb
 python_06_함수형프로그래밍.ipynb
 python_07_class.ipynb
 python_08_파일입출력.ipynb
 python_09_정규표현식.ipynb
 python_10_numpy.ipynb
 python_11_numpy.ipynb
 python_12_numpy.ipynb
 python_13_데이터수집.ipynb
 python_14_데이터수집_정적데이터.ipynb
 python_15_hollys.ipynb
'python_16_데이터수집_정적데이터_도시별 기상청 날씨.ipynb'
 python_17_selenium.ipynb
 python_18_json.ipynb
'python_19_공공데이터 자전거 사고 다발 지역.ipynb'
'python_20_기상청 관광 코스별

### 파일 형식 데이터 불러오기

In [ ]:
# 읽어오는 파일에 컬럼명이 없으면 header = None 을 설정한다.
# 그렇지 않으면 첫 번째 줄을 컬럼명으로 인식을 하기 때문이다.
# header 파라미터의 default : 'infer'
data = pd.read_csv('pdsample/num.txt', header = None)
data

0  1  2  3   4
0  1  2  3  4   5
1  6  7  8  9  10

In [ ]:
type(data)
print(data)

   0  1  2  3   4
0  1  2  3  4   5
1  6  7  8  9  10


In [ ]:
# 컬럼(열)
print(data[0])
print(data[1])

print(data[0][0])

print(data[0:1])

print(type(data[0]))

0    1
1    6
Name: 0, dtype: int64
0    2
1    7
Name: 1, dtype: int64
1
   0  1  2  3  4
0  1  2  3  4  5
<class 'pandas.core.series.Series'>


In [ ]:
# index(행)
print(data.iloc[0]) # 0번째 행의 값을 리턴

print(type(data.iloc[0])) # Series

0    1
1    2
2    3
3    4
4    5
Name: 0, dtype: int64
<class 'pandas.core.series.Series'>


In [ ]:
# .values 하면 numpy 포맷으로 변환한다.
# 내부적으로 numpy로 되어 있기 때문에 가능하다.
print(data.values)
print(type(data.values)) # ndarray

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
<class 'numpy.ndarray'>


In [ ]:
dir(data)

['T',
 '_AXIS_LEN',
 '_AXIS_ORDERS',
 '_AXIS_REVERSED',
 '_AXIS_TO_AXIS_NUMBER',
 '_HANDLED_TYPES',
 '__abs__',
 '__add__',
 '__and__',
 '__annotations__',
 '__array__',
 '__array_priority__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex

In [ ]:
# numpy 참고
a = np.arange(12).reshape(3, 4)
print(a)
print(a[1][2])
print(a[1])
print(a[1, 2]) # 2번 행의(1 인덱스) 2번째 열(2 인덱스)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
6
[4 5 6 7]
6


In [ ]:
# python list 참고
b = [[0, 1, 2, 3], 
     [4, 5, 6, 7], 
     [8, 9, 10, 11]]

print(b[1][2])
print(b[1])
# print(b[1, 2:]) # list에서는 슬라이싱 적용이 안됨

6
[4, 5, 6, 7]


### 웹 주소에서 데이터 불러오기

In [5]:
# header는 기본이 첫 줄을 컬럼명으로 가져오도록 설정이 되어 있기 때문에 header='infer' 생략 가능하다.
data = pd.read_csv('https://raw.githubusercontent.com/mwaskom/seaborn-data/master/tips.csv', header = 'infer') # header = 'infer' 기본값
data

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [ ]:
# 전반적인 데이터 정보 확인
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    object 
 3   smoker      244 non-null    object 
 4   day         244 non-null    object 
 5   time        244 non-null    object 
 6   size        244 non-null    int64  
dtypes: float64(2), int64(1), object(4)
memory usage: 13.5+ KB


In [ ]:
# 기본적으로 앞의 5개를 보여줌
data.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [ ]:
# 마지막 5개를 보여줌
data.tail()

total_bill   tip     sex smoker   day    time  size
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

In [ ]:
# random으로 1개씩 보여줌
data.sample()

total_bill   tip   sex smoker  day    time  size
42       13.94  3.06  Male     No  Sun  Dinner     2

In [ ]:
# 보여줄 갯수를 지정할 수 있음
# data.head(10)
#data.tail(10)
data.sample(10)

total_bill   tip     sex smoker   day    time  size
72        26.86  3.14  Female    Yes   Sat  Dinner     2
197       43.11  5.00  Female    Yes  Thur   Lunch     4
26        13.37  2.00    Male     No   Sat  Dinner     2
105       15.36  1.64    Male    Yes   Sat  Dinner     2
57        26.41  1.50  Female     No   Sat  Dinner     2
111        7.25  1.00  Female     No   Sat  Dinner     1
17        16.29  3.71    Male     No   Sun  Dinner     3
101       15.38  3.00  Female    Yes   Fri  Dinner     2
89        21.16  3.00    Male     No  Thur   Lunch     2
157       25.00  3.75  Female     No   Sun  Dinner     4

In [ ]:
data.index

RangeIndex(start=0, stop=244, step=1)

In [ ]:
data.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [ ]:
# dict 타입
dictdata = {'name':'홍길동', 'age':'30'}
dictdata['name']
# dictdata.name

'홍길동'

In [ ]:
dir(dict)
dict.items

<method 'items' of 'dict' objects>

In [ ]:
# pandas는 dictionary와 attribute 방식 모두 가져올 수 있다.
# dictionary 방식 이용
data['tip']
data['tip'][2]

3.5

In [ ]:
data.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [ ]:
# attribute 방식 이용
data.tip

0      1.01
1      1.66
2      3.50
3      3.31
4      3.61
       ... 
239    5.92
240    2.00
241    2.00
242    1.75
243    3.00
Name: tip, Length: 244, dtype: float64

In [ ]:
# data['tip', 'day']

# 컬럼을 fancying indexing을 이용해서 가져올 때 index를 이용해서 가져올 수 있다.
# data[[0, 2]]

data[['tip', 'day']]

tip   day
0    1.01   Sun
1    1.66   Sun
2    3.50   Sun
3    3.31   Sun
4    3.61   Sun
..    ...   ...
239  5.92   Sat
240  2.00   Sat
241  2.00   Sat
242  1.75   Sat
243  3.00  Thur

[244 rows x 2 columns]

In [ ]:
# 컬럼을 slicing을 이용해서 가져올 수 없다.
# data['tip' : 'day']

# row를 slicing을 이용해서 가져올 때는 index를 이용해서 가져온다.
data[1:5]

total_bill   tip     sex smoker  day    time  size
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [ ]:
# KeyError
# data[3]

data.iloc[3]

total_bill     23.68
tip             3.31
sex             Male
smoker            No
day              Sun
time          Dinner
size               2
Name: 3, dtype: object

하나의 컬럼 또는 행을 가져오면 Series로 리턴한다.  
fancy indexing을 이용해서 하나의 컬럼 또는 행을 가져오면 Dataframe으로 한다.


In [ ]:
type(data.iloc[3])

pandas.core.series.Series

In [ ]:
type(data['tip']) # Series
# type(data.tip) #series

pandas.core.series.Series

In [ ]:
type(data[['tip']]) # DataFrame (fancy indexing 사용을 하면 데이터 타입을 그대로 가져온다.)

pandas.core.frame.DataFrame

In [ ]:
data.iloc[0:5]
data.iloc[0:5, :]

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [ ]:
data.iloc[[0, 3, 5]] # fancy indexing  행을 뜻함. 행이 없다면 열을 뜻함 /   data[['tip', 'smoker', 'day']]

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
3       23.68  3.31    Male     No  Sun  Dinner     2
5       25.29  4.71    Male     No  Sun  Dinner     4

In [ ]:
print(data.iloc[3]) # 3행
print(data.iloc[3][1]) # 3행 1열 / list : a[3][1] / array : a[3, 1]

total_bill     23.68
tip             3.31
sex             Male
smoker            No
day              Sun
time          Dinner
size               2
Name: 3, dtype: object
3.31


In [ ]:
data.iloc[0:3, 1:4] # slicing

tip     sex smoker
0  1.01  Female     No
1  1.66    Male     No
2  3.50    Male     No

In [ ]:
data.iloc[[0, 3, 5], [1, 4, 5]] # 행, 열

tip  day    time
0  1.01  Sun  Dinner
3  3.31  Sun  Dinner
5  4.71  Sun  Dinner

iloc는 indexer를 이용해서 가져오고, loc를 이름을 이용해서 가져온다.

In [ ]:
# 행은 이름이 설정되어 있지 않아서 자동으로 생성된 Range Index가 이름이 된다.
data.loc[0, 'tip']

1.01

In [ ]:
data.loc[0:5, 'tip' : 'time']

tip     sex smoker  day    time
0  1.01  Female     No  Sun  Dinner
1  1.66    Male     No  Sun  Dinner
2  3.50    Male     No  Sun  Dinner
3  3.31    Male     No  Sun  Dinner
4  3.61  Female     No  Sun  Dinner
5  4.71    Male     No  Sun  Dinner

In [ ]:
data.loc[[0, 3, 5], ['tip', 'day', 'time']]

tip  day    time
0  1.01  Sun  Dinner
3  3.31  Sun  Dinner
5  4.71  Sun  Dinner

#### at

이름으로 한 위치의 값만 가져온다.

In [ ]:
print(data.at[0, 'tip'])
print(data.loc[0, 'tip'])
print(data.iloc[0, 1])

1.01
1.01
1.01


In [ ]:
 # at은 slicing indexing 적용이 안된다.
data.at[0:3, 'tip']

TypeError: ignored

In [ ]:
# at은 fancying indexing을 사용할 수 없다.
data.at[[1, 3, 5], ['tip', 'smoker', 'day']]

TypeError: ignored

#### iat

iat는 인덱스 번호로 한 위치의 값을 가져온다.


In [ ]:
# data.at[0, 1] KeyError
data.at[0, 'tip']

1.01

In [ ]:
data.iat[0, 1] # .iat[행, 열]

1.01

In [ ]:
# iat는 slicing을 사용할 수 없다.
data.iat[0:3, 1]

ValueError: ignored

In [ ]:
# data.tip >= 5
data['tip'] >= 5

0      False
1      False
2      False
3      False
4      False
       ...  
239     True
240    False
241    False
242    False
243    False
Name: tip, Length: 244, dtype: bool

In [ ]:
data[data['tip'] >= 5] # data[True, False, True ....]

total_bill    tip     sex smoker   day    time  size
11        35.26   5.00  Female     No   Sun  Dinner     4
23        39.42   7.58    Male     No   Sat  Dinner     4
39        31.27   5.00    Male     No   Sat  Dinner     3
44        30.40   5.60    Male     No   Sun  Dinner     4
46        22.23   5.00    Male     No   Sun  Dinner     2
47        32.40   6.00    Male     No   Sun  Dinner     4
52        34.81   5.20  Female     No   Sun  Dinner     4
59        48.27   6.73    Male     No   Sat  Dinner     4
73        25.28   5.00  Female    Yes   Sat  Dinner     2
83        32.68   5.00    Male    Yes  Thur   Lunch     2
85        34.83   5.17  Female     No  Thur   Lunch     4
88        24.71   5.85    Male     No  Thur   Lunch     2
116       29.93   5.07    Male     No   Sun  Dinner     4
141       34.30   6.70    Male     No  Thur   Lunch     6
142       41.19   5.00    Male     No  Thur   Lunch     5
143       27.05   5.00  Female     No  Thur   Lunch     6
155       29.85   5.14  Female     No   Sun  Dinner     5
156       48.17   5.00    Male     No   Sun  Dinner     6
170       50.81  10.00    Male    Yes   Sat  Dinner     3
172        7.25   5.15    Male    Yes   Sun  Dinner     2
181       23.33   5.65    Male    Yes   Sun  Dinner     2
183       23.17   6.50    Male    Yes   Sun  Dinner     4
185       20.69   5.00    Male     No   Sun  Dinner     5
197       43.11   5.00  Female    Yes  Thur   Lunch     4
211       25.89   5.16    Male    Yes   Sat  Dinner     4
212       48.33   9.00    Male     No   Sat  Dinner     4
214       28.17   6.50  Female    Yes   Sat  Dinner     3
239       29.03   5.92    Male     No   Sat  Dinner     3

In [ ]:
data.tip
data['tip']
a = data[data['tip'] >= 5] # DataFrame
# a['tip']
data[data['tip'] >= 5]['tip']

data['tip'] # Serise
data['tip'][3] # Serise index

3.31

In [ ]:
data[data['tip'] >= 5].loc[:, 'tip':'day']

tip     sex smoker   day
11    5.00  Female     No   Sun
23    7.58    Male     No   Sat
39    5.00    Male     No   Sat
44    5.60    Male     No   Sun
46    5.00    Male     No   Sun
47    6.00    Male     No   Sun
52    5.20  Female     No   Sun
59    6.73    Male     No   Sat
73    5.00  Female    Yes   Sat
83    5.00    Male    Yes  Thur
85    5.17  Female     No  Thur
88    5.85    Male     No  Thur
116   5.07    Male     No   Sun
141   6.70    Male     No  Thur
142   5.00    Male     No  Thur
143   5.00  Female     No  Thur
155   5.14  Female     No   Sun
156   5.00    Male     No   Sun
170  10.00    Male    Yes   Sat
172   5.15    Male    Yes   Sun
181   5.65    Male    Yes   Sun
183   6.50    Male    Yes   Sun
185   5.00    Male     No   Sun
197   5.00  Female    Yes  Thur
211   5.16    Male    Yes   Sat
212   9.00    Male     No   Sat
214   6.50  Female    Yes   Sat
239   5.92    Male     No   Sat

In [ ]:
data[data['tip'] >= 5].iloc[:, 1:5]

tip     sex smoker   day
11    5.00  Female     No   Sun
23    7.58    Male     No   Sat
39    5.00    Male     No   Sat
44    5.60    Male     No   Sun
46    5.00    Male     No   Sun
47    6.00    Male     No   Sun
52    5.20  Female     No   Sun
59    6.73    Male     No   Sat
73    5.00  Female    Yes   Sat
83    5.00    Male    Yes  Thur
85    5.17  Female     No  Thur
88    5.85    Male     No  Thur
116   5.07    Male     No   Sun
141   6.70    Male     No  Thur
142   5.00    Male     No  Thur
143   5.00  Female     No  Thur
155   5.14  Female     No   Sun
156   5.00    Male     No   Sun
170  10.00    Male    Yes   Sat
172   5.15    Male    Yes   Sun
181   5.65    Male    Yes   Sun
183   6.50    Male    Yes   Sun
185   5.00    Male     No   Sun
197   5.00  Female    Yes  Thur
211   5.16    Male    Yes   Sat
212   9.00    Male     No   Sat
214   6.50  Female    Yes   Sat
239   5.92    Male     No   Sat

요일이 'Sun' 이거나 'Sat'의 tip과 day의 값 가져오기

In [ ]:
data[(data['day'] == 'Sun') | (data['day'] == 'Sat')][['tip', 'day']]

a = data[(data['day'] == 'Sun') | (data['day'] == 'Sat')]
a['day'].unique() # 'Sun'과 'Sat'만 데이터로 가져왔는지 확인하기 위해
a[['tip', 'day']]

tip  day
0    1.01  Sun
1    1.66  Sun
2    3.50  Sun
3    3.31  Sun
4    3.61  Sun
..    ...  ...
238  4.67  Sat
239  5.92  Sat
240  2.00  Sat
241  2.00  Sat
242  1.75  Sat

[163 rows x 2 columns]

In [ ]:
# len([1,2,3])
# len('123')
# len({'a':1,'b':2,'c':3})
# len(data)

# [1,2,3].size # AttributeError
# '123'.size # AttributeError
# {'a':1,'b':2,'c':3}.size # AttributeError
np.array([1,2,3]).size

data.size # 244 * 7
data['tip'].size

data.tip

0      1.01
1      1.66
2      3.50
3      3.31
4      3.61
       ... 
239    5.92
240    2.00
241    2.00
242    1.75
243    3.00
Name: tip, Length: 244, dtype: float64

In [ ]:
# 컬럼명을 바꿀 때 mapper, columns 옵션을 이용해서 변경할 수 있다.
data2 = data.rename(mapper = {'size' : 'size_'}, axis = 1)
data2 = data.rename(columns = {'size' : 'size_'})
data2

total_bill   tip     sex smoker   day    time  size_
0         16.99  1.01  Female     No   Sun  Dinner      2
1         10.34  1.66    Male     No   Sun  Dinner      3
2         21.01  3.50    Male     No   Sun  Dinner      3
3         23.68  3.31    Male     No   Sun  Dinner      2
4         24.59  3.61  Female     No   Sun  Dinner      4
..          ...   ...     ...    ...   ...     ...    ...
239       29.03  5.92    Male     No   Sat  Dinner      3
240       27.18  2.00  Female    Yes   Sat  Dinner      2
241       22.67  2.00    Male    Yes   Sat  Dinner      2
242       17.82  1.75    Male     No   Sat  Dinner      2
243       18.78  3.00  Female     No  Thur  Dinner      2

[244 rows x 7 columns]

#### category

- category는 문자열(object)보다 더 많은 기능을 할 수 있다.

- category는 문자 또는 숫자도 가능하다.

- category는 몇 개로 분류할 수 있을 때 사용한다. ex) 성별(남, 여)

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    object 
 3   smoker      244 non-null    object 
 4   day         244 non-null    object 
 5   time        244 non-null    object 
 6   size        244 non-null    int64  
dtypes: float64(2), int64(1), object(4)
memory usage: 13.5+ KB


In [8]:
type(data['sex'])

pandas.core.series.Series

In [9]:
print(data['sex'].dtype) # 문자열로 되어 있는 값은 dtype이 object이다.

object


In [11]:
# object를 category로 데이터 타입으로 변경한다.
# astype 데이터 타입 변경
data['sex'] = data['sex'].astype('category')

In [12]:
data.info() # sex의 dtype이 object에서 category로 변경됨

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype   
---  ------      --------------  -----   
 0   total_bill  244 non-null    float64 
 1   tip         244 non-null    float64 
 2   sex         244 non-null    category
 3   smoker      244 non-null    object  
 4   day         244 non-null    object  
 5   time        244 non-null    object  
 6   size        244 non-null    int64   
dtypes: category(1), float64(2), int64(1), object(3)
memory usage: 11.9+ KB


In [13]:
data.sample()

total_bill   tip   sex smoker   day   time  size
192       28.44  2.56  Male    Yes  Thur  Lunch     2

In [21]:
# data에서 Female만 가져오기
# data[data['sex'] == 'Female']
# data[data['sex'] == 'Female']['sex'].unique()
data[data.sex == 'Female']

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
11        35.26  5.00  Female     No   Sun  Dinner     4
14        14.83  3.02  Female     No   Sun  Dinner     2
16        10.33  1.67  Female     No   Sun  Dinner     3
..          ...   ...     ...    ...   ...     ...   ...
226       10.09  2.00  Female    Yes   Fri   Lunch     2
229       22.12  2.88  Female    Yes   Sat  Dinner     2
238       35.83  4.67  Female     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[87 rows x 7 columns]

In [23]:
# data[data['sex'] == 'Female']['sex'].unique()
data[data.sex == 'Female']['sex'].unique()

['Female']
Categories (2, object): ['Female', 'Male']

금요일에 방문한 여자만 가져오기

In [28]:
data['day'].unique()
# dictionary 방식
data['day'] == 'Fri'
data[(data['day'] == 'Fri') & (data['sex'] == 'Female')] 

# attribute 방식

data[(data.day == 'Fri') & (data.sex == 'Female')] 

total_bill   tip     sex smoker  day    time  size
92         5.75  1.00  Female    Yes  Fri  Dinner     2
93        16.32  4.30  Female    Yes  Fri  Dinner     2
94        22.75  3.25  Female     No  Fri  Dinner     2
100       11.35  2.50  Female    Yes  Fri  Dinner     2
101       15.38  3.00  Female    Yes  Fri  Dinner     2
221       13.42  3.48  Female    Yes  Fri   Lunch     2
223       15.98  3.00  Female     No  Fri   Lunch     3
225       16.27  2.50  Female    Yes  Fri   Lunch     2
226       10.09  2.00  Female    Yes  Fri   Lunch     2

In [35]:
data[(data['day'] == 'Fri') & (data['sex'] == 'Female')]['sex'].unique()

data[(data['day'] == 'Fri') & (data['sex'] == 'Female')]['day'].unique()

data[(data.day == 'Fri') & (data.sex == 'Female')]['day'].unique()

data[(data.day == 'Fri') & (data.sex == 'Female')]['sex'].unique()

['Female']
Categories (2, object): ['Female', 'Male']

#### describe

- 기초적인 통계 분석을 해준다.

In [36]:
# describe( ) 의 기본은 데이터가 숫자로 된 컬럼만 가져온다.
data.describe()

total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [38]:
type(data.describe()) # DataFrame

pandas.core.frame.DataFrame

In [39]:
# pandas는 numpy기반이여서 numpy의 기능을 사용할 수 있다.
data.describe().T # T 전치 행렬

count       mean       std   min      25%     50%      75%    max
total_bill  244.0  19.785943  8.902412  3.07  13.3475  17.795  24.1275  50.81
tip         244.0   2.998279  1.383638  1.00   2.0000   2.900   3.5625  10.00
size        244.0   2.569672  0.951100  1.00   2.0000   2.000   3.0000   6.00

describe()는 기본적으로 숫자형 데이터만 분석한다.  
include 옵션을 사용하면 다른 분석할 데이터 타입을 지정할 수 있다.

In [42]:
data.describe(include=['object'])
data.describe(include=['object']).T

count unique     top freq
smoker   244      2      No  151
day      244      4     Sat   87
time     244      2  Dinner  176

In [44]:
data.describe(include=['float64', 'object', 'int64'])
data.describe(include=['float64', 'object', 'int64']).T

count unique     top freq       mean       std   min      25%  \
total_bill  244.0    NaN     NaN  NaN  19.785943  8.902412  3.07  13.3475   
tip         244.0    NaN     NaN  NaN   2.998279  1.383638   1.0      2.0   
smoker        244      2      No  151        NaN       NaN   NaN      NaN   
day           244      4     Sat   87        NaN       NaN   NaN      NaN   
time          244      2  Dinner  176        NaN       NaN   NaN      NaN   
size        244.0    NaN     NaN  NaN   2.569672    0.9511   1.0      2.0   

               50%      75%    max  
total_bill  17.795  24.1275  50.81  
tip            2.9   3.5625   10.0  
smoker         NaN      NaN    NaN  
day            NaN      NaN    NaN  
time           NaN      NaN    NaN  
size           2.0      3.0    6.0

In [46]:
# 데이터 타입이 object 일때만 가져온다.
# data.describe(include=['object'])
data.describe(include='O') # 대문자 알파벳 O

smoker  day    time
count     244  244     244
unique      2    4       2
top        No  Sat  Dinner
freq      151   87     176

In [47]:
np.number

numpy.number

In [50]:
data.describe(include=['float64'])
data.describe(include=np.number)

total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [51]:
# 모든 타입의 데이터를 분석할 때는 include='all'로 설정한다.
data.describe(include='all')

total_bill         tip   sex smoker  day    time        size
count   244.000000  244.000000   244    244  244     244  244.000000
unique         NaN         NaN     2      2    4       2         NaN
top            NaN         NaN  Male     No  Sat  Dinner         NaN
freq           NaN         NaN   157    151   87     176         NaN
mean     19.785943    2.998279   NaN    NaN  NaN     NaN    2.569672
std       8.902412    1.383638   NaN    NaN  NaN     NaN    0.951100
min       3.070000    1.000000   NaN    NaN  NaN     NaN    1.000000
25%      13.347500    2.000000   NaN    NaN  NaN     NaN    2.000000
50%      17.795000    2.900000   NaN    NaN  NaN     NaN    2.000000
75%      24.127500    3.562500   NaN    NaN  NaN     NaN    3.000000
max      50.810000   10.000000   NaN    NaN  NaN     NaN    6.000000

In [53]:
# day컬럼의 요소갯수 244개
data['day'].values # day의 요소 값
data['day'].size # day의 요소 갯수

244

In [55]:
# value_counts( )는 unique한 값과 그 개수를 알려준다.(Serise만 사용한다.)
data['day'].value_counts()

Sat     87
Sun     76
Thur    62
Fri     19
Name: day, dtype: int64

In [56]:
data['sex'].value_counts()

Male      157
Female     87
Name: sex, dtype: int64

In [57]:
data['size'].value_counts()

2    156
3     38
4     37
5      5
1      4
6      4
Name: size, dtype: int64

In [62]:
# 주말 고객수와 평일 고객수 구하기
a = (data['day'] == 'Sat') | (data['day'] == 'Sun')
a.value_counts() # True 163 (주말 고객수) / False 81 (평일 고객수)

True     163
False     81
Name: day, dtype: int64

In [65]:
print(1 in [1, 2, 3, 4]) # True
print(5 in [1, 2, 3, 4]) # False

True
False


In [67]:
# 같은 컬럼에 있는 값을 가지고 검식할 때 isin( )을 사용할 수 있다.
b = data['day'].isin({'Sun', 'Sat'})
b.value_counts()

True     163
False     81
Name: day, dtype: int64

In [68]:
b.unique()

array([ True, False])

#### Where

In [75]:
a = np.array([10, 20, 30, 40, 50])
a

array([10, 20, 30, 40, 50])

In [76]:
# where의 인자는 조건이다.
# 조건만 넣을 경우 True의 위치를 리턴한다.
np.where(a > 30) # 인덱스 값을 리턴한다.

(array([3, 4]),)

In [78]:
# where은 인자 갯수에 따라서 기능이 달라진다.
# 조건이 True이면 0, False이면 100을 반환한다.
np.where(a > 30, 0, 100)

array([100, 100, 100,   0,   0])

describe 결과를 pandas에서 제공하는 함수

In [79]:
data.describe()

total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [80]:
data['tip'].count()

244

In [81]:
data['tip'].mean()

2.99827868852459

In [82]:
data['tip'].max()

10.0

In [83]:
data['tip'].min()

1.0

In [84]:
data['tip'].std()

1.3836381890011822

describe( ) 결과를 numpy에서 제공하는 함수

In [99]:
import numpy.ma as ma

In [97]:
kk = data.values[:, 1].copy()  # numpy에서 copy()는 deepcopy가 발생
kk

array([1.01, 1.66, 3.5, 3.31, 3.61, 4.71, 2.0, 3.12, 1.96, 3.23, 1.71,
       5.0, 1.57, 3.0, 3.02, 3.92, 1.67, 3.71, 3.5, 3.35, 4.08, 2.75,
       2.23, 7.58, 3.18, 2.34, 2.0, 2.0, 4.3, 3.0, 1.45, 2.5, 3.0, 2.45,
       3.27, 3.6, 2.0, 3.07, 2.31, 5.0, 2.24, 2.54, 3.06, 1.32, 5.6, 3.0,
       5.0, 6.0, 2.05, 3.0, 2.5, 2.6, 5.2, 1.56, 4.34, 3.51, 3.0, 1.5,
       1.76, 6.73, 3.21, 2.0, 1.98, 3.76, 2.64, 3.15, 2.47, 1.0, 2.01,
       2.09, 1.97, 3.0, 3.14, 5.0, 2.2, 1.25, 3.08, 4.0, 3.0, 2.71, 3.0,
       3.4, 1.83, 5.0, 2.03, 5.17, 2.0, 4.0, 5.85, 3.0, 3.0, 3.5, 1.0,
       4.3, 3.25, 4.73, 4.0, 1.5, 3.0, 1.5, 2.5, 3.0, 2.5, 3.48, 4.08,
       1.64, 4.06, 4.29, 3.76, 4.0, 3.0, 1.0, 4.0, 2.55, 4.0, 3.5, 5.07,
       1.5, 1.8, 2.92, 2.31, 1.68, 2.5, 2.0, 2.52, 4.2, 1.48, 2.0, 2.0,
       2.18, 1.5, 2.83, 1.5, 2.0, 3.25, 1.25, 2.0, 2.0, 2.0, 2.75, 3.5,
       6.7, 5.0, 5.0, 2.3, 1.5, 1.36, 1.63, 1.73, 2.0, 2.5, 2.0, 2.74,
       2.0, 2.0, 5.14, 5.0, 3.75, 2.61, 2.0, 3.5, 2.5, 2.0, 2.0, 3.

In [105]:
# tips 데이터 셋에서 tip만 가져옴
xx = ma.array(data.values[:, 1])
print(type(xx))
xx

<class 'numpy.ma.core.MaskedArray'>


masked_array(data=[1.01, 1.66, 3.5, 3.31, 3.61, 4.71, 2.0, 3.12, 1.96,
                   3.23, 1.71, 5.0, 1.57, 3.0, 3.02, 3.92, 1.67, 3.71,
                   3.5, 3.35, 4.08, 2.75, 2.23, 7.58, 3.18, 2.34, 2.0,
                   2.0, 4.3, 3.0, 1.45, 2.5, 3.0, 2.45, 3.27, 3.6, 2.0,
                   3.07, 2.31, 5.0, 2.24, 2.54, 3.06, 1.32, 5.6, 3.0, 5.0,
                   6.0, 2.05, 3.0, 2.5, 2.6, 5.2, 1.56, 4.34, 3.51, 3.0,
                   1.5, 1.76, 6.73, 3.21, 2.0, 1.98, 3.76, 2.64, 3.15,
                   2.47, 1.0, 2.01, 2.09, 1.97, 3.0, 3.14, 5.0, 2.2, 1.25,
                   3.08, 4.0, 3.0, 2.71, 3.0, 3.4, 1.83, 5.0, 2.03, 5.17,
                   2.0, 4.0, 5.85, 3.0, 3.0, 3.5, 1.0, 4.3, 3.25, 4.73,
                   4.0, 1.5, 3.0, 1.5, 2.5, 3.0, 2.5, 3.48, 4.08, 1.64,
                   4.06, 4.29, 3.76, 4.0, 3.0, 1.0, 4.0, 2.55, 4.0, 3.5,
                   5.07, 1.5, 1.8, 2.92, 2.31, 1.68, 2.5, 2.0, 2.52, 4.2,
                   1.48, 2.0, 2.0, 2.18, 1.5, 2.83, 1.5,

In [101]:
ma.count(xx)

244

In [109]:
# ma.max(xx) # AttributeError
# xx.max() # AttributeError
type(xx) # numpy.ma.core.MaskedArray
type(kk) # numpy.ndarray
kk.max()

10.0