<a href="https://colab.research.google.com/github/eoooomji/python_demo_colab/blob/master/python_11_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 3차원 이상에서 차원 구분법

In [ ]:
import numpy as np

In [ ]:
# 0부터 24미만 까지 생성
b = np.arange(24).reshape(2, 3, 4)
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [ ]:
# print하면 array라는 글자는 안보인다.
# 공백은 그대로 보인다. -> 차원 구분이 가능하다.
print(b)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [ ]:
b[0]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
b[1]

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
b[0, 1]

array([4, 5, 6, 7])

In [ ]:
b[1, 1]

array([16, 17, 18, 19])

In [ ]:
b[0, 1, 3]

7

## fancy indexing과 indexing의 차이

- indexing은 원래 차원에서 하나 감소해서 가져온다.

- fancy indexing은 원래 차원에서 그대로 가져온다.

In [ ]:
# indexing은 차원이 하나 감소해서 가져온다. (3차원 > 2차원)
b[0]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
# fancy indexing은 원래 3차원 그대로 가져온다.
b[[0]]

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

In [ ]:
# b[0]은 b[0,:,:]의 단축 표현이다.
b[[0], :, :]

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

In [ ]:
# b의 0번째 공간, 1번째 행 미만, 열 전체
b[0, :1, :]

array([[0, 1, 2, 3]])

## Ellipsis

...(Ellipsis)은 이후로 모든 것을 의미한다.

In [ ]:
type(...)

ellipsis

In [ ]:
b[0, :, :]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
b[0, ...]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
print(b[0]) # 생략기법
print(b[0, :, :]) # slicing 기법
print(b[0, ...]) # Ellipsis 기법

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
# 숫자 1, 5, 9 가져오기
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [ ]:
b[0, : , 1]

array([1, 5, 9])

In [ ]:
# 숫자 1, 5, 9, 3, 7, 11 가져오기
b[0, ...]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
print(b[0, :, [1,3]])

[[ 1  5  9]
 [ 3  7 11]]


In [ ]:
# 숫자 4, 5, 6, 7, 16, 17, 18, 19 가져오기
b[:, 1, :]

array([[ 4,  5,  6,  7],
       [16, 17, 18, 19]])

In [ ]:
b[:, 1 : 2, :]

array([[[ 4,  5,  6,  7]],

       [[16, 17, 18, 19]]])

In [ ]:
# 숫자 3, 7, 11, 15, 19, 23 가져오기
print(b[ :, :, 3])
print('================')
print(b[ :, :, 3:])
print('================')
print(b[ :, :, -1])
print('================')
print(b[ :, :, [3]])

[[ 3  7 11]
 [15 19 23]]
[[[ 3]
  [ 7]
  [11]]

 [[15]
  [19]
  [23]]]
[[ 3  7 11]
 [15 19 23]]
[[[ 3]
  [ 7]
  [11]]

 [[15]
  [19]
  [23]]]


In [ ]:
c = b[:, :, 3]
c.shape
c

array([[ 3,  7, 11],
       [15, 19, 23]])

## 줄임표현(...)

출력해야할 데이터 수가 엄청 클 때 보이는 ...은 Ellipsis와는 다르다.

In [ ]:
# out에 나오는 ...은 단순한 줄임표현이다.
np.arange(100000)

array([    0,     1,     2, ..., 99997, 99998, 99999])

In [ ]:
# 앞, 뒤로 6개의 값이 더 나온다.
np.set_printoptions(edgeitems=6)
np.arange(100000)

array([    0,     1,     2,     3,     4,     5, ..., 99994, 99995, 99996,
       99997, 99998, 99999])

## 연산

numpy연산의 기본은 두 개의 shape이 같아야 한다.

In [ ]:
a = np.arange(12).reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a.shape

(3, 4)

In [ ]:
b = np.arange(1, 13).reshape(3, 4)
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
b.shape

(3, 4)

numpy는 elementwise로 vectorize연산을 한다.  
vectorize는 데이터의 연산을 일관적으로 처리하는 기능이다.

In [ ]:
# 같은 위치의 원소끼리 더해준다.(elementwise)
a + b

array([[ 1,  3,  5,  7],
       [ 9, 11, 13, 15],
       [17, 19, 21, 23]])

In [ ]:
# python의 list에서 연산자는 elementwise가 아니라 list를 확장시킨다.(연결)
[1, 2, 3] + [4, 5, 6]

[1, 2, 3, 4, 5, 6]

In [ ]:
@np.vectorize
def plus(a, b) :
  return a + b

plus([1, 2, 3], [4, 5, 6]) # elementwise, vectorize

array([5, 7, 9])

In [ ]:
a = np.arange(6).reshape(2, 3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
b = np.arange(6, 12).reshape(2, 3)
b

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
a * b # elementwise

array([[ 0,  7, 16],
       [27, 40, 55]])

In [ ]:
# python의 list끼리 * (곱하기)를 할 수 없다.
[1, 2, 3] * [4, 5, 6]

TypeError: ignored

## matrix
numpy에서는 ndarray이외에 matrix라는 자료형도 존재한다.  
matrix에서는 * (곱하기) 연산자는 행렬곱을 의미한다.

In [ ]:
type(np.array(3))

numpy.ndarray

In [ ]:
c = np.matrix([[1, 2,], [3, 4]])
c

matrix([[1, 2],
        [3, 4]])

In [ ]:
type(c)

numpy.matrix

행렬 곱
```
a  b    *   a  b    =   (a*a)+(b*c)  (a*b)+(b*d)
c  d        c  d        (c*a)+(d*c)  (c*b)+(d*d)


```

In [ ]:
# matrix * matrix = 행렬곱
c * c

matrix([[ 7, 10],
        [15, 22]])

ndarray에서 행렬곱 연산자는 @이다.  
python재단에서 numpy를 위해 만들어준 연산자이다.

In [ ]:
a.shape

(2, 3)

In [ ]:
b.shape

(2, 3)

In [ ]:
a @ b

ValueError: ignored

행렬곱을 하기 위해서는 shape가 맞아야 한다.  
T는 tranpose(전치)의 약자이다.

In [ ]:
a

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
# 전치 행렬 : 행과 열을 바꾼다.
a.T

array([[0, 3],
       [1, 4],
       [2, 5]])

In [ ]:
a @ a.T

array([[ 5, 14],
       [14, 50]])

matrix는 @와 * 모두가 가능하다.

In [ ]:
c @ c.T

matrix([[ 5, 11],
        [11, 25]])

In [ ]:
c * c.T

matrix([[ 5, 11],
        [11, 25]])

함수 방법으로 np.dot()을 사용할 수 있다.

In [ ]:
np.dot(a, a.T) #ndarray

array([[ 5, 14],
       [14, 50]])

In [ ]:
np.dot(c, c.T) #matrix

matrix([[ 5, 11],
        [11, 25]])

method방법으로도 행렬곱을 할 수 있다.  
function방법과 사용하는 방법이 다르므로 주의한다.

In [ ]:
np.dot(a, a.T) # function(함수) 방식

array([[ 5, 14],
       [14, 50]])

In [ ]:
a.dot(a.T) # method 방식

array([[ 5, 14],
       [14, 50]])

## broadcasting

python은 배열과 숫자간에 연산을 할 수 있다.  



In [ ]:
[1, 2, 3] + 1

TypeError: ignored

[1, 2, 3] + 1 => (x)  
[1, 2, 3] + [1, 2, 3] => (o)  연결  
[1, 2, 3] * 1 => (o)  반복  
[1, 2, 3] * [1, 2, 3] => (x)


In [ ]:
a = np.arange(6).reshape(2, 3) # ndarry
a

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
a + 1

array([[1, 2, 3],
       [4, 5, 6]])

broadcasting이랑 모양(shape)이 안맞아도 특정 조건에 성립하면  
모양을 같게 만들어 연산을 해주는 기능이다.

위 연산에서 1을 a와 같은 모양으로 만들어 준다. 
```
a + 1 
=> [[1, 1, 1],
    [1, 1, 1]]
```


### 1. broadcasting이 안되는 경우와 가능한 경우

In [ ]:
a # 2행 3열

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
a + np.array([3, 4])

ValueError: ignored

In [ ]:
a + np.array([3, 4, 5])

array([[ 3,  5,  7],
       [ 6,  8, 10]])

In [ ]:
# broadcasting으로 인해 2행 3열로 바뀌어 계산이 된다.
# [1, 1, 1]
# [2, 2, 2]
# 위처럼 바뀌어 더하기가 된다.
a + np.array([[1], [2]])

array([[1, 2, 3],
       [5, 6, 7]])

## strides

strides는 다음 원소끼리의 메모리 크기를 차원별로 알려준다.  
c의 포인터 개념을 알고 있으면 이해하기가 쉽다.

In [ ]:
a = np.arange(12).reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
# 행의 메모리 간격은 32bytes
# 열의 메모리 간격은 4bytes
a.strides

(32, 8)

In [ ]:
a.dtype

dtype('int64')

In [ ]:
a.itemsize

8

In [ ]:
# 열의 원소 개수 * itemsize = 행의 메모리 간격
# itemsize = 열의 메모리 간격
a.shape

(3, 4)

In [ ]:
# 메모리 저장시 행 단위 / 열 단위 처리가 있다.
[[1, 2, 3],
 [4, 5, 6]]
# 행 단위 저장시
# 1 2 3 4 5 6

# 열 단위 저장시
# 1 4 2 5 3 6


## axis

axis는 다차원 배열을 연산할 때 기준이 되는 축이다.

(0, 0), (0, 1), (0, 2), (0, 3)  
(1, 0), (1, 1), (1, 2), (1, 3)  
(2, 0), (2, 1), (2, 2), (2, 3)

In [ ]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
np.sum(a)

66

In [ ]:
# a배열은 2차원이므로 axis=0 은 행 기준(행마다)을 의미한다.
np.sum(a, axis = 0)

array([12, 15, 18, 21])

In [ ]:
# a배열은 2차원이므로 axis=1 은 열 기준(열마다)를 의미한다.
np.sum(a, axis = 1)

array([ 6, 22, 38])

In [ ]:
np.sum(a, axis = 2)

array([[ 6, 22, 38],
       [54, 70, 86]])

axis는 3차원 이상에서도 사용할 수 있다.

3차원은 행렬에 공간(깊이) 개념이 추가되었다고 할 수 있다.

2차원(axis = 0, axis = 1) (행, 열)

3차원(axis =0, axis = 1, axis = 2) (공간, 행, 열)

(0, 0, 0), (0, 0, 1), (0, 0, 2), (0, 0, 3)  
(0, 1, 0), (0, 1, 1), (0, 1, 2), (0, 1, 3)  
(0, 2, 0), (0, 2, 1), (0, 2, 2), (0, 2, 3)

(1, 0, 0), (1, 0, 1), (1, 0, 2), (1, 0, 3)  
(1, 1, 0), (1, 1, 1), (1, 1, 2), (1, 1, 3)  
(1, 2, 0), (1, 2, 1), (1, 2, 2), (1, 2, 3)

In [ ]:
a = np.arange(24).reshape(2, 3, 4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [ ]:
# a.sum(axis = 0)
# 공간기준(공간마다)
np.sum(a, axis = 0) 

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [ ]:
# a.sum(axis = 1)
# 행 기준(행마다)
np.sum(a, axis = 1)

array([[12, 15, 18, 21],
       [48, 51, 54, 57]])

In [ ]:
# a.sum(axis = 2)
# 열 기준(열마다)
np.sum(a, axis = 2)

array([[ 6, 22, 38],
       [54, 70, 86]])

## array 모양 바꾸기


### 1. reshape

reshape은 차원을 바꿔주는 기능을 한다.

In [ ]:
# signatuer대로 하면 a.reshape((3, 8))로 작성해야 한다.
# 하지만 reshape(3, 8)로 작성을 해도 내부적으로 이상 없이 처리한다.
# reshape 수행 후의 값은 그대로 있다.
a = np.arange(24).reshape(3, 8)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [ ]:
a = np.arange(24)
b = a.reshape(3, 8)

a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [ ]:
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [ ]:
a = np.arange(24).reshape(3, 8)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [ ]:
a.reshape(2, 3, 4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [ ]:
# ValueError : 크기가 맞지 않음
a.reshape(2, 3, 5)

ValueError: ignored

In [ ]:
# 음수를 쓰면 알아서 shape을 맞춘다.
# 음수의 크기는 상관 없다.
a.reshape(2, 3, -1)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [ ]:
a.reshape(3, 5, -1)

ValueError: ignored

In [ ]:
# 음수는 2개를 사용할 수 없다.
# 음수는 다른 차원들이 정해준 상황에서 남은 하나의 차원만 알아서 맞춰준다.
a.reshape(3, -1, -1)

ValueError: ignored

In [ ]:
a.reshape(3, -1, 8)

array([[[ 0,  1,  2,  3,  4,  5,  6,  7]],

       [[ 8,  9, 10, 11, 12, 13, 14, 15]],

       [[16, 17, 18, 19, 20, 21, 22, 23]]])

### 2. reshape으로 차원 늘리기

In [ ]:
# 2차원
a = np.arange(6).reshape(2, 3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
# 3차원
a = np.arange(6).reshape(2, 3, 1)
a

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]]])

## resize

- size는 원소 개수를 알려준다.

- reshape과의 차이점  
  1. mutable이다. return이 없고 자기 자신을 바꾼다.
  
  2. 원래의 원소 개수와 변경하는 원소의 개수가 안 맞아도 된다.(0으로 채워준다.)


In [ ]:
a = np.arange(24)
# 원소의 개수
print(a.size)
print(len(a))
a

24
24


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [ ]:
# a.resize(2, 3, 1)
np.resize(a, (2, 3, 1))

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]]])

In [ ]:
np.resize(a, (3, 2, 4))

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [ ]:
a.reshape(2, 3, 1)

ValueError: ignored

In [ ]:
# 빈 공간은 0으로 채워줌
b = np.arange(24)
b.resize((2, 3, 8))
b

array([[[ 0,  1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20, 21, 22, 23]],

       [[ 0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0]]])

## array 쪼개기

split

In [ ]:
a = np.arange(24)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [ ]:
# a는 바뀌지 않으므로 재할당한다.
a = np.split(a, 3, axis = 0)
a

[array([0, 1, 2, 3, 4, 5, 6, 7]),
 array([ 8,  9, 10, 11, 12, 13, 14, 15]),
 array([16, 17, 18, 19, 20, 21, 22, 23])]

In [ ]:
print(type(a))
print(type(a[0]))

<class 'list'>
<class 'numpy.ndarray'>


In [ ]:
b = np.arange(24)
b = np.split(b, 2)
b

[array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]),
 array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])]