<a href="https://colab.research.google.com/github/eoooomji/python_demo_colab/blob/master/python_10_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy

- Numpy는 Numercal python의 줄임마로, 파이썬에서 산술 계산을 위한 가장 필수 패키지 중 하나이다.

- 과학 계산을 위한 대부분의 패키지는 Numpy의 배열 객체를 데이터 교환을 위한 공통 언어처럼 사용한다.

- 효율적인 다차원 배열인 ndarray(n dimensional array)는 빠른 배열 계산과 유연한 브로드 캐스팅 기능을 제공한다.

- 반복문을 작성할 필요 없이 전체 데이터 배열을 빠르게 계산할 수 있는 표준 수학 함수이다.

- 배열 데이터를 디스크에 쓰거나 읽을 수 있는 도구와 메모리에 적대된 파일을 다루는 도구이다.

- 선형대수, 난수 생성기 등에 사용한다.

- C, C++, 포트란으로 작성한 코드를 연결할 수 있는 C API가 제공된다.

- numpy는 8바이트이다.(64비트)

공식 문서  

https://numpy.org/doc/stable/

numpy 100 문제

https://github.com/rougier/numpy-100

## 1. 데이터 생성

In [ ]:
# !pip install numpy
import numpy as np

In [ ]:
a = np.zeros(3) # 1차원 배열 = 벡터
a

array([0., 0., 0.])

In [ ]:
print(a)

[0. 0. 0.]


In [ ]:
# 처음 객체들은 type(), dir()을 해본다.
print(type(a))
print(dir(a))

<class 'numpy.ndarray'>
['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_prepare__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '__reduce_ex__', '__repr__', '__r

In [ ]:
# 1차원 배열 = 벡터
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [ ]:
print(a)
print(type(a))
print(dir(a))
print(len(dir(a)))

[1 2 3]
<class 'numpy.ndarray'>
['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_prepare__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '__reduce_ex__', '__repr_

In [ ]:
# 2차원 배열 = 행렬
b = np.array([[1, 2], [3, 4]])
b

array([[1, 2],
       [3, 4]])

In [ ]:
print(b)
print(type(b))
print(dir(b))
print(len(dir(b)))

[[1 2]
 [3 4]]
<class 'numpy.ndarray'>
['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_prepare__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '__reduce_ex__', '

In [ ]:
# 3차원 이상 배열 = 텐서(tensor)
c = np.array([[[1, 2], [3, 4]], 
             [[5, 6], [7, 8]]])
c

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [ ]:
print(c)
print(type(c))
print(dir(c))
print(len(dir(c)))

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
<class 'numpy.ndarray'>
['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_prepare__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__

In [ ]:
# 문자 데이터가 하나라도 있으면 전체가 문자로 바뀐다.
# numpy는 homogeneous 이다. numpy는 배열이며 안의 데이터는 같은 동일 취급이 된다.
a = np.array([1, '2', 3])
print(a)
print(type(a))
print(type(a[0]))

['1' '2' '3']
<class 'numpy.ndarray'>
<class 'numpy.str_'>


In [ ]:
b = np.array(['a', 1, True])
print(b)
print(type(b))
b

['a' '1' 'True']
<class 'numpy.ndarray'>


array(['a', '1', 'True'], dtype='<U21')

In [ ]:
c = np.array([1, True, 2, False])
print(c)
print(type(c))
c
print(type(c[0]))

[1 1 2 0]
<class 'numpy.ndarray'>
<class 'numpy.int64'>


#### np.zeros

- tuple로 인자를 넣으면 그대로 모양을 만든다.

- (2, 3) : 2행 3열 행렬을 만든다.

- zeros는 기본값으로 0. (실수)로 값을 모두 채운다.  
a = np.zeros((2, 3))  
a = np.zeros([2, 3])


In [ ]:
a = np.zeros([2, 3])
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
c = np.zeros([2, 3, 2])
c

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

#### np.eye

- eye는 단위 행렬

- 숫자만 사용할 수 있다.

In [ ]:
# 인자값이 1개이면 행과 열이 같다.
# 3행 3열 행렬을 생성한다.
a = np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# EYE는 행과 열의 크기를 지정 할 수 있다.
# 3행 2열 행렬을 생성한다.
b = np.eye(3, 2)
b

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [ ]:
# 크기(1)가 시작되는 위치를 지정 할 수 있다.
c = np.eye(4, k = 0)
c

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
c = np.eye(4, k = 1)
c

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

#### np.identity

- 수학에서 단위행렬은 영어로 identity matrix이다.

- 크기 한개만 지정해서 생성할 수 있다.

In [ ]:
a = np.identity(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# TypeError
# 인자 하나만 지정할 수 있다.
b = np.identity(3, 2)
b

TypeError: ignored

#### np.full

- 지정한 크기의 배열을 생성하고 채울 값을 지정한다.

In [ ]:
# 2행 2열의 행렬을 생성하고 1로 초기화 해준다.
a = np.full((2, 2), 1)
a

array([[1, 1],
       [1, 1]])

In [ ]:
# 1행 3열의 행렬을 생성하고 4로 초기화 해준다.
b = np.full(3, 4)
b

array([4, 4, 4])

In [ ]:
c = np.full((2, 2), [1, 3])
c

array([[1, 3],
       [1, 3]])

In [ ]:
d = np.full((2, 2), [[1, 2], [3, 4]])
d

array([[1, 2],
       [3, 4]])

#### np.empty

- 배열을 생성하고 초기화를 지정하지 않는다.

- 메모리에 있는 값이나 이전에 사용했던 값들로 채워진다.

In [ ]:
a = np.empty(3)
a

array([2.27661023e-316, 0.00000000e+000, 0.00000000e+000])

In [ ]:
k = np.zeros((2, 3))
k

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
# zeros해서 생성한 배열이 있으면 배열의 값을 0으로 채워준다.
b = np.empty((2, 3))
b

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
# 임의의 값이 넘어간다. 의미는 따로 없다.
c = np.empty((2, 5))
c

array([[3.04870677e-316, 1.77863633e-322, 0.00000000e+000,
        0.00000000e+000, 2.41907520e-312],
       [4.22762483e-062, 3.27042565e+179, 6.50217611e-091,
        1.13876943e-042, 3.99662193e-315]])

#### np.ones

- 배열의 모든 값을 1. 로 초기화 해준다.

In [ ]:
# 1행 3열의 배열 생성 후 모든 값을 1로 채운다.
a = np.ones(3)
a

array([1., 1., 1.])

In [ ]:
# b = np.ones((2, 3))
b = np.ones([2, 3])
b

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
c = np.empty((2, 3))
c 

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
e = np.eye(3, 4)
e

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [ ]:
d = np.empty((3, 4))
d

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [ ]:
e = np.full((3, 4), 0)
e

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [ ]:
# empty는 값을 지정해 두면 데이터를 그대로 갖고 오지 않는다.
f = np.empty((3, 4))
f

array([[3.00236499e-316, 0.00000000e+000, 9.17479904e-321,
        1.24813274e-316],
       [6.91690076e-310, 6.91690076e-310, 6.91690076e-310,
        6.91690076e-310],
       [0.00000000e+000, 4.94065646e-324, 2.12199579e-314,
        4.44659081e-323]])

#### _like

- _like가 붙으면 shpae이 같게 만들어 진다.

- 연산하기 위해서 shape를 맞춰야 하는 경우에 사용한다.

In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# 모양을 알기 위해선 shape 메소드를 이용하면 된다.
a.shape

(2, 3)

In [ ]:
b = np.empty_like(a)
b

array([[4607182418800017408, 4607182418800017408, 4607182418800017408],
       [4607182418800017408, 4607182418800017408, 4607182418800017408]])

In [ ]:
c = np.eye(2)
c

array([[1., 0.],
       [0., 1.]])

In [ ]:
c.shape

(2, 2)

In [ ]:
d = np.eye(3)
d

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
d.shape

(3, 3)

In [ ]:
# ValueError
# 모양이 다르기 때문에 연산을 할 수 없다.
c + d

ValueError: ignored

#### linspace

- 동등한 간격으로 값을 생성한다.

- 0 부터 49 까지 50개가 생성 된다면 세번째 num인자 값이 생략되어 있으므로  
start와 end를 계산해서 default값 50이 생성된다.   
  
  linspace(start, end, num)  
  linspace(0, 49) # num = 50

In [ ]:
a = np.linspace(0, 49)
a

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38.,
       39., 40., 41., 42., 43., 44., 45., 46., 47., 48., 49.])

In [ ]:
len(a)

50

In [ ]:
# 위에 a 에서 default값으로 50개가 생성되었으므로 임의의 값이 b에서 50개가 생성 되었다.
b = np.linspace(1, 5)
b

array([1.        , 1.08163265, 1.16326531, 1.24489796, 1.32653061,
       1.40816327, 1.48979592, 1.57142857, 1.65306122, 1.73469388,
       1.81632653, 1.89795918, 1.97959184, 2.06122449, 2.14285714,
       2.2244898 , 2.30612245, 2.3877551 , 2.46938776, 2.55102041,
       2.63265306, 2.71428571, 2.79591837, 2.87755102, 2.95918367,
       3.04081633, 3.12244898, 3.20408163, 3.28571429, 3.36734694,
       3.44897959, 3.53061224, 3.6122449 , 3.69387755, 3.7755102 ,
       3.85714286, 3.93877551, 4.02040816, 4.10204082, 4.18367347,
       4.26530612, 4.34693878, 4.42857143, 4.51020408, 4.59183673,
       4.67346939, 4.75510204, 4.83673469, 4.91836735, 5.        ])

In [ ]:
len(b)

50

In [ ]:
# 1부터 10까지 3개의 요소를 생성한다.
# 기본은 endpoint = True로 설정되어 있기 때문에 10이 포함이 된다.
np.linspace(1, 10, 3)

array([ 1. ,  5.5, 10. ])

In [ ]:
# 1부터 10미만 사이에서 3개의 요소를 생성한다.
# endpoint = Fales로 설정되어 있어서 10을 포함하지 않는다.
np.linspace(1, 10, 3, endpoint = False)

array([1., 4., 7.])

#### logspace

- linspace와 비슷하다.

- log scale을 사용하는 차이가 있다.

- 1부터 50까지 사이에 10개의 요소를 생성한다.  
np.logspace(1, 50, 10)

In [ ]:
np.logspace(1, 50, 10)

array([1.00000000e+01, 2.78255940e+06, 7.74263683e+11, 2.15443469e+17,
       5.99484250e+22, 1.66810054e+28, 4.64158883e+33, 1.29154967e+39,
       3.59381366e+44, 1.00000000e+50])

## *dtype*

numpy는 c언어를 기반으로 해서 만들었기 때문에 c의 데이터 타입을 차용할 수 있다.


In [ ]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [ ]:
print(type(a))
print(a.dtype)

<class 'numpy.ndarray'>
int64


In [ ]:
b = np.array([1, 2, 3], dtype = np.int8)
b

array([1, 2, 3], dtype=int8)

In [ ]:
# np.int8은 -128 ~ 127 사이의 값을 저장할 수 있다.
c = np.array([-127, -128, 17, 2, 3, -127, 127, -128], dtype = np.int8)
c

array([-127, -128,   17,    2,    3, -127,  127, -128], dtype=int8)

In [ ]:
type(c[0])8

numpy.int8

In [ ]:
# int는 python의 int를 사용한다.
d = np.array([127, 2, 3, -127, -128], dtype = int)
d

array([ 127,    2,    3, -127, -128])

In [ ]:
type(d[0])

numpy.int64

# python 도움말

In [ ]:
?sum

In [ ]:
help(sum)

Help on built-in function sum in module builtins:

sum(iterable, /, start=0)
    Return the sum of a 'start' value (default: 0) plus an iterable of numbers
    
    When the iterable is empty, return the start value.
    This function is intended specifically for use with numeric values and may
    reject non-numeric types.



# numpy 도움말

In [ ]:
np.lookfor('sum')

In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6]])
# array의 shape을 알려준다.
a.shape

(2, 3)

In [ ]:
# array가 몇 차원인지 알려준다.
# shape으로도 알 수 있다.
a.ndim

2

In [ ]:
# 데이터 타입을 알려준다.
a.dtype

dtype('int64')

In [ ]:
# 요소의 개수를 알려준다.
# shape으로도 알 수 있다.
a.size

6

In [ ]:
# 요소당 byte수를 알려준다.
a.itemsize

8

# numpy와 python의 속도 차이

- 값이 작을 때는 속도가 비슷하다.

- 값이 커지면 속도 차이가 난다. (numpy를 이용하면 속도가 더 빠름)

In [ ]:
np.arange(10) # range와 같음

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# numpy를 이용한 계산
%time np.sum(np.arange(1000000))

CPU times: user 1.95 ms, sys: 5.33 ms, total: 7.28 ms
Wall time: 7.95 ms


499999500000

In [ ]:
# python을 이용한 계산
%time sum(range(1000000))

CPU times: user 24.5 ms, sys: 825 µs, total: 25.4 ms
Wall time: 25.1 ms


499999500000

In [ ]:
%time np.sum(np.arange(1000000000))

CPU times: user 1.55 s, sys: 2.96 s, total: 4.51 s
Wall time: 4.51 s


499999999500000000

In [ ]:
%time sum(range(1000000000))

CPU times: user 22.3 s, sys: 0 ns, total: 22.3 s
Wall time: 22.2 s


499999999500000000

# copy

대입문 6가지

a = 1

a = b = 1

a, b = 1, 2

a, *b = 1, 2, 3

a += 1

global, nonlocal

## python에서 copy

In [ ]:
# heterogeneous, sequence, mutable
a = [1, 2, 3]

In [ ]:
b = a

In [ ]:
b

[1, 2, 3]

In [ ]:
a is b # 메모리 주소 비교

True

In [ ]:
# a와 b가 메모리 주소를 공유
# b값을 변경하면 a값도 변한다.
b[0] = 7

In [ ]:
b

[7, 2, 3]

In [ ]:
a

[7, 2, 3]

list copy

In [ ]:
a = [1, 2, 3]

In [ ]:
# copy()는 똑같은 값만 갖고 메모리는 공유하지 않는다.
b = a.copy()

In [ ]:
a is b

False

In [ ]:
id(a)

139999313557120

In [ ]:
id(b)

139999313252992

In [ ]:
# 값의 비교
a == b

True

In [ ]:
b[0] = 8
print(a)
print(b)

[1, 2, 3]
[8, 2, 3]


In [ ]:
print(a is b)
print(a == b)

False
False


2차원 list copy

In [ ]:
a = [[1, 2, 3]]
a

[[1, 2, 3]]

In [ ]:
# shallow copy 발생
b = a.copy()

In [ ]:
print(a is b)
print(a == b)

False
True


In [ ]:
print(a[0] is b[0])
print(a[0] == b[0])

True
True


list deep copy

In [ ]:
import copy

In [ ]:
a = [[1, 2, 3]]
b = copy.deepcopy(a)

In [ ]:
print(a)
print(b)

[[1, 2, 3]]
[[1, 2, 3]]


In [ ]:
print(a is b)
print(a == b)
print(a[0] is b[0])
print(a[0] == b[0])

False
True
False
True


슬라이싱 [:] : 전체라는 뜻  
- 슬라이싱 방식으로 1차 리스트 일때 재할당 시 deepcopy가 발생한다.  

- 2차열 리스트 이상인 경우에는 shallow copy가 발생한다.

In [ ]:
a = [1, 2, 3]
b = a[:]
print(b)
print(a is b)
print(a == b)
b[0] = 7
print(a is b)
print(a == b)

[1, 2, 3]
False
True
False
False


In [ ]:
# 슬라이싱 2차 이상인 경우 shallow copy가 발생한다.
a = [[1, 2, 3]]
b = a[:]
print(b)
print(a is b)
print(a == b)
b[0][0] = 7
print(a)
print(b)
print(a[0] is b[0])
print(a == b)

[[1, 2, 3]]
False
True
[[7, 2, 3]]
[[7, 2, 3]]
True
True


※ python의 copy는 기본적으로 shallow copy를 한다.

## numpy의 copy

In [ ]:
a = b = np.array([1, 2, 3])

In [ ]:
print(a is b)
print(a == b)

True
[ True  True  True]


array는 sequence타입으로 인덱싱과 슬라이싱이 가능하다.

In [ ]:
a[0] #indexing

1

In [ ]:
a[:] # slicing

array([1, 2, 3])

In [ ]:
# array는 mutable이다.
# 예외가 몇가지 있지만 mutable에 가깝다.
a[0] = 100
print(a)
print(b)

[100   2   3]
[100   2   3]


array는 homogeneous, sequence, mutable 이다.

array deepcopy

In [ ]:
a = np.array([[1, 2, 3]])
# numpy는 기본적으로 deepcopy이다.
b = a.copy()

In [ ]:
print(a is b)

False


In [ ]:
print(a[0] is b[0])

False


## as 계열

다른 데이터 타입을 가져와서 바꿔서 사용할 때는 as라는 이름이 보통 붙는다.

In [ ]:
# python의 list데이터 타입을 int ndarray로 변환
a = [1, 2, 3] # python의 list
print(type(a))
print(type(a[0]))
b = np.array(a)
print(type(b))
print(type(b[0]))

<class 'list'>
<class 'int'>
<class 'numpy.ndarray'>
<class 'numpy.int64'>


In [ ]:
# python의 list데이터 타입을 int ndarray로 변환 (asarray())
a = [1, 2, 3] # python의 list
print(type(a))
print(type(a[0]))
b = np.asarray(a)
print(type(b))
print(type(b[0]))

<class 'list'>
<class 'int'>
<class 'numpy.ndarray'>
<class 'numpy.int64'>


In [ ]:
# python의 list데이터 타입을 float ndarray로 변환
a = [1, 2, 3] # python의 list
print(type(a))
print(type(a[0]))
b = np.asfarray(a)
print(type(b))
print(type(b[0]))

<class 'list'>
<class 'int'>
<class 'numpy.ndarray'>
<class 'numpy.float64'>


In [ ]:
# python의 list 데이터 타입이 float이면 float ndarray로 변환
# python의 list 데이터 타입이 int이면 int ndarray로 변환
a = [1., 2., 3.]
print(type(a))
print(type(a[0]))

b = np.asarray(a)
print(type(b))
print(type(b[0]))

c = np.array(a)
print(type(c))
print(type(c[0]))

<class 'list'>
<class 'float'>
<class 'numpy.ndarray'>
<class 'numpy.float64'>
<class 'numpy.ndarray'>
<class 'numpy.float64'>


# 값 가져오기

## comma로 값 가져오기

In [ ]:
a = [[1, 2, 3], [4, 5, 6]] # python
b = np.array([[1, 2, 3], [4, 5, 6]]) # numpy

# 1차원 리스트로 가져온다.
a[0]

[1, 2, 3]

In [ ]:
# TypeError
a[0, 1]

TypeError: ignored

python은 슬라이스 함수를 이용해서 comma를 사용하는 방법은 가능하다.

In [ ]:
# 2차원 리스트로 가져온다.
a[slice(0, 1)] # 0행부터 1행 미만의 데이터를 가져온다.

[[1, 2, 3]]

In [ ]:
a[slice(0, 2)] # 0행부터 2행 미만의 데이터를 가져온다.

[[1, 2, 3], [4, 5, 6]]

In [ ]:
a[0:2]

[[1, 2, 3], [4, 5, 6]]

numpy는 기본적으로 인덱싱 / 슬라이싱을 할 때 comma를 사용할 수 있다.

In [ ]:
# numpy
# b[행, 열]
print(b[0, 2])
print(b[0, -1])

3
3


In [ ]:
# python
# a[행][열]
print(a[0][2])
print(a[0][-1])

3
3


## boolean indexing

numpy에서 boolean indexing 조건

- array만 가능하다.

- numpy True, False로만 가능하다.

- shape이 맞아야 한다. (개수가 맞을 때만 사용할 수 있다.)

- python에서는 지원하지 않는다.

In [ ]:
a = [[1, 2, 3, 4]] # python list

In [ ]:
# TypeError
a > 3

TypeError: ignored

In [ ]:
b = np.array([1, 2, 3, 4])
b

array([1, 2, 3, 4])

array를 scalar와 연산하면 elementwise로 계산한다.  
(elementwise : 원소별로 각각 계산이 된다.)

In [ ]:
# 원소별로 비교해서 True / False 로 계산한다.
# 1 > 2, 2 > 2, 3 > 2, 4 > 2

# numpy에서는 가능하고 python에서는 안된다.
b > 2

array([False, False,  True,  True])

numpy는 indexing, slicing 자리에 조건도 쓸 수 있다.  
True에 해당되는 값만 가져온다.

In [ ]:
# boolean indexing
b[np.array([False, False, True, True])]

array([3, 4])

In [ ]:
b[b > 2]

array([3, 4])

In [ ]:
a = [1, 2, 3, 4]
a[True, True, False, False]

TypeError: ignored

## fancy indexing

In [ ]:
# reshape 모양을 바꿀 때 사용한다.
b = np.arange(100).reshape(20, 5) # 20행 5열로 모양을 바꾼다.
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84],
       [85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94],
       [95, 96, 97, 98, 99]])

인덱싱, 슬라이싱 자리에 괄호를 하나 삽입하면 fancy indexing을 적용 할 수 있다.

여러개를 한 번에 인덱싱 할 수 있다.

In [ ]:
b[:] # 전체를 가져온다. b[:.:] 와 같다.
print(b[0,:]) # 0번째의 행을 전부 가져온다.
# b[행, 열]
print(b[1:3]) # 1행부터 3행 미만의 데이터를 가져온다.
print(b[1:3, 2:4]) # 1행부터 3행 미만이면서 2열부터 4열 미만의 데이터를 가져온다.
print((b[[1, 3, 5]])) # b[[1, 3, 5], :] 1행, 3행, 5행의 데이터를 가져온다.
print(b[[1, 3, 5], [0, 2, 4]]) # 1행 1열(0인덱스), 3행 3열(2인덱스), 5행 5열(4인덱스)의 데이터를 가져온다.

[0 1 2 3 4]
[[ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 7  8]
 [12 13]]
[[ 5  6  7  8  9]
 [15 16 17 18 19]
 [25 26 27 28 29]]
[ 5 17 29]


fancying indexing은 인덱싱 기법만 사용할 수 있다.  
' : ' (콜론)은 슬라이싱 기법이므로 지원하지 않는다.


In [ ]:
# Error
b[[2:5]]

SyntaxError: ignored

In [ ]:
# 갯수가 같게 지정되어야 한다.
b[[1, 3, 4], [0, 2, 1]] # 정상처리

array([ 5, 17, 21])

In [ ]:
b[[1, 3, 4], [0, 2]] # IndexError

IndexError: ignored